package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsAccountInfo;

public interface TsAccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_account_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_account_info
     *
     * @mbg.generated
     */
    int insert(TsAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_account_info
     *
     * @mbg.generated
     */
    int insertSelective(TsAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_account_info
     *
     * @mbg.generated
     */
    TsAccountInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_account_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_account_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsAccountInfo record);
}