package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsCaseBasicInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TsCaseBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_case_basic_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_case_basic_info
     *
     * @mbg.generated
     */
    int insert(TsCaseBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_case_basic_info
     *
     * @mbg.generated
     */
    int insertSelective(TsCaseBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_case_basic_info
     *
     * @mbg.generated
     */
    TsCaseBasicInfo selectByPrimaryKey(String id);

    List<TsCaseBasicInfo> selectByGroupId(@Param(value = "groupId") String groupId);

    List<TsCaseBasicInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_case_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsCaseBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_case_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsCaseBasicInfo record);
}