package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsDictionary;

public interface TsDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dictionary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dictionary
     *
     * @mbg.generated
     */
    int insert(TsDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dictionary
     *
     * @mbg.generated
     */
    int insertSelective(TsDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dictionary
     *
     * @mbg.generated
     */
    TsDictionary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsDictionary record);
}