package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsEnvironmentList;

public interface TsEnvironmentListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_environment_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_environment_list
     *
     * @mbg.generated
     */
    int insert(TsEnvironmentList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_environment_list
     *
     * @mbg.generated
     */
    int insertSelective(TsEnvironmentList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_environment_list
     *
     * @mbg.generated
     */
    TsEnvironmentList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_environment_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsEnvironmentList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_environment_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsEnvironmentList record);
}