package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsGroupInfo;

public interface TsGroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_group_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_group_info
     *
     * @mbg.generated
     */
    int insert(TsGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_group_info
     *
     * @mbg.generated
     */
    int insertSelective(TsGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_group_info
     *
     * @mbg.generated
     */
    TsGroupInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TsGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsGroupInfo record);
}