package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsInterfaceParameter;

public interface TsInterfaceParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_parameter
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_parameter
     *
     * @mbg.generated
     */
    int insert(TsInterfaceParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_parameter
     *
     * @mbg.generated
     */
    int insertSelective(TsInterfaceParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_parameter
     *
     * @mbg.generated
     */
    TsInterfaceParameter selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_parameter
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsInterfaceParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_parameter
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsInterfaceParameter record);
}