package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsInterfaceBasicInfo;
import com.bgw.testing.dao.bgw_automation.pojo.TsInterfaceBasicInfoWithBLOBs;

public interface TsInterfaceBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_basic_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_basic_info
     *
     * @mbg.generated
     */
    int insert(TsInterfaceBasicInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_basic_info
     *
     * @mbg.generated
     */
    int insertSelective(TsInterfaceBasicInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_basic_info
     *
     * @mbg.generated
     */
    TsInterfaceBasicInfoWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsInterfaceBasicInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TsInterfaceBasicInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_interface_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsInterfaceBasicInfo record);
}