package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsMysqlInfo;
import com.bgw.testing.dao.bgw_automation.pojo.TsMysqlInfoWithBLOBs;

public interface TsMysqlInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_mysql_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_mysql_info
     *
     * @mbg.generated
     */
    int insert(TsMysqlInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_mysql_info
     *
     * @mbg.generated
     */
    int insertSelective(TsMysqlInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_mysql_info
     *
     * @mbg.generated
     */
    TsMysqlInfoWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_mysql_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsMysqlInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_mysql_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TsMysqlInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_mysql_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsMysqlInfo record);
}