package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsResource;

public interface TsResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resource
     *
     * @mbg.generated
     */
    int insert(TsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resource
     *
     * @mbg.generated
     */
    int insertSelective(TsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resource
     *
     * @mbg.generated
     */
    TsResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsResource record);
}