package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsReportCaseResult;

public interface TsReportCaseResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_case_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_case_result
     *
     * @mbg.generated
     */
    int insert(TsReportCaseResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_case_result
     *
     * @mbg.generated
     */
    int insertSelective(TsReportCaseResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_case_result
     *
     * @mbg.generated
     */
    TsReportCaseResult selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_case_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsReportCaseResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_case_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsReportCaseResult record);
}