package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsRedisInfo;

public interface TsRedisInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_redis_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_redis_info
     *
     * @mbg.generated
     */
    int insert(TsRedisInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_redis_info
     *
     * @mbg.generated
     */
    int insertSelective(TsRedisInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_redis_info
     *
     * @mbg.generated
     */
    TsRedisInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_redis_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsRedisInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_redis_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsRedisInfo record);
}