package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsReportStepResult;
import com.bgw.testing.dao.bgw_automation.pojo.TsReportStepResultWithBLOBs;

public interface TsReportStepResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_step_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_step_result
     *
     * @mbg.generated
     */
    int insert(TsReportStepResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_step_result
     *
     * @mbg.generated
     */
    int insertSelective(TsReportStepResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_step_result
     *
     * @mbg.generated
     */
    TsReportStepResultWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_step_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsReportStepResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_step_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TsReportStepResultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_step_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsReportStepResult record);
}