package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsReportResult;

public interface TsReportResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_result
     *
     * @mbg.generated
     */
    int insert(TsReportResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_result
     *
     * @mbg.generated
     */
    int insertSelective(TsReportResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_result
     *
     * @mbg.generated
     */
    TsReportResult selectByPrimaryKey(String batchNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsReportResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_report_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsReportResult record);
}