package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsRoleResource;

public interface TsRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbg.generated
     */
    int insert(TsRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbg.generated
     */
    int insertSelective(TsRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbg.generated
     */
    TsRoleResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsRoleResource record);
}