package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsRoleInfo;

public interface TsRoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_info
     *
     * @mbg.generated
     */
    int insert(TsRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_info
     *
     * @mbg.generated
     */
    int insertSelective(TsRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_info
     *
     * @mbg.generated
     */
    TsRoleInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsRoleInfo record);
}