package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsRoleAccount;

public interface TsRoleAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_account
     *
     * @mbg.generated
     */
    int insert(TsRoleAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_account
     *
     * @mbg.generated
     */
    int insertSelective(TsRoleAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_account
     *
     * @mbg.generated
     */
    TsRoleAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsRoleAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsRoleAccount record);
}