package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsStepBasicInfo;

import java.util.List;

public interface TsStepBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_step_basic_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_step_basic_info
     *
     * @mbg.generated
     */
    int insert(TsStepBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_step_basic_info
     *
     * @mbg.generated
     */
    int insertSelective(TsStepBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_step_basic_info
     *
     * @mbg.generated
     */
    TsStepBasicInfo selectByPrimaryKey(String id);

    List<TsStepBasicInfo> selectByCaseId(String caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_step_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsStepBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_step_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsStepBasicInfo record);
}