package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsTaskProperty;

public interface TsTaskPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_property
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_property
     *
     * @mbg.generated
     */
    int insert(TsTaskProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_property
     *
     * @mbg.generated
     */
    int insertSelective(TsTaskProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_property
     *
     * @mbg.generated
     */
    TsTaskProperty selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_property
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsTaskProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_property
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TsTaskProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_property
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsTaskProperty record);
}