package com.bgw.testing.dao.bgw_automation.mapper;

import com.bgw.testing.dao.bgw_automation.pojo.TsTaskConfig;

public interface TsTaskConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_config
     *
     * @mbg.generated
     */
    int insert(TsTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_config
     *
     * @mbg.generated
     */
    int insertSelective(TsTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_config
     *
     * @mbg.generated
     */
    TsTaskConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_task_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsTaskConfig record);
}