package com.bgw.testing.dao.bgw_automation.pojo;

import java.util.Date;

public class TsAccountInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.login_account
     *
     * @mbg.generated
     */
    private String loginAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.login_passward
     *
     * @mbg.generated
     */
    private String loginPassward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.encry_key
     *
     * @mbg.generated
     */
    private String encryKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.contact_phone
     *
     * @mbg.generated
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.contact_email
     *
     * @mbg.generated
     */
    private String contactEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_account_info.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.id
     *
     * @return the value of ts_account_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.id
     *
     * @param id the value for ts_account_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.login_account
     *
     * @return the value of ts_account_info.login_account
     *
     * @mbg.generated
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.login_account
     *
     * @param loginAccount the value for ts_account_info.login_account
     *
     * @mbg.generated
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount == null ? null : loginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.login_passward
     *
     * @return the value of ts_account_info.login_passward
     *
     * @mbg.generated
     */
    public String getLoginPassward() {
        return loginPassward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.login_passward
     *
     * @param loginPassward the value for ts_account_info.login_passward
     *
     * @mbg.generated
     */
    public void setLoginPassward(String loginPassward) {
        this.loginPassward = loginPassward == null ? null : loginPassward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.encry_key
     *
     * @return the value of ts_account_info.encry_key
     *
     * @mbg.generated
     */
    public String getEncryKey() {
        return encryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.encry_key
     *
     * @param encryKey the value for ts_account_info.encry_key
     *
     * @mbg.generated
     */
    public void setEncryKey(String encryKey) {
        this.encryKey = encryKey == null ? null : encryKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.user_name
     *
     * @return the value of ts_account_info.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.user_name
     *
     * @param userName the value for ts_account_info.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.contact_phone
     *
     * @return the value of ts_account_info.contact_phone
     *
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.contact_phone
     *
     * @param contactPhone the value for ts_account_info.contact_phone
     *
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.contact_email
     *
     * @return the value of ts_account_info.contact_email
     *
     * @mbg.generated
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.contact_email
     *
     * @param contactEmail the value for ts_account_info.contact_email
     *
     * @mbg.generated
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail == null ? null : contactEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.status
     *
     * @return the value of ts_account_info.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.status
     *
     * @param status the value for ts_account_info.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.remark
     *
     * @return the value of ts_account_info.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.remark
     *
     * @param remark the value for ts_account_info.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.create_time
     *
     * @return the value of ts_account_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.create_time
     *
     * @param createTime the value for ts_account_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.create_by
     *
     * @return the value of ts_account_info.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.create_by
     *
     * @param createBy the value for ts_account_info.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.update_time
     *
     * @return the value of ts_account_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.update_time
     *
     * @param updateTime the value for ts_account_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_account_info.update_by
     *
     * @return the value of ts_account_info.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_account_info.update_by
     *
     * @param updateBy the value for ts_account_info.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}