package com.bgw.testing.dao.bgw_automation.pojo;

import java.util.Date;

public class TsCaseBasicInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_case_basic_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_case_basic_info.group_id
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_case_basic_info.case_name
     *
     * @mbg.generated
     */
    private String caseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_case_basic_info.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_case_basic_info.step_id
     *
     * @mbg.generated
     */
    private String stepId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_case_basic_info.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_case_basic_info.is_invalid
     *
     * @mbg.generated
     */
    private Boolean isInvalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_case_basic_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_case_basic_info.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_case_basic_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_case_basic_info.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_case_basic_info.id
     *
     * @return the value of ts_case_basic_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_case_basic_info.id
     *
     * @param id the value for ts_case_basic_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_case_basic_info.group_id
     *
     * @return the value of ts_case_basic_info.group_id
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_case_basic_info.group_id
     *
     * @param groupId the value for ts_case_basic_info.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_case_basic_info.case_name
     *
     * @return the value of ts_case_basic_info.case_name
     *
     * @mbg.generated
     */
    public String getCaseName() {
        return caseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_case_basic_info.case_name
     *
     * @param caseName the value for ts_case_basic_info.case_name
     *
     * @mbg.generated
     */
    public void setCaseName(String caseName) {
        this.caseName = caseName == null ? null : caseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_case_basic_info.description
     *
     * @return the value of ts_case_basic_info.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_case_basic_info.description
     *
     * @param description the value for ts_case_basic_info.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_case_basic_info.step_id
     *
     * @return the value of ts_case_basic_info.step_id
     *
     * @mbg.generated
     */
    public String getStepId() {
        return stepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_case_basic_info.step_id
     *
     * @param stepId the value for ts_case_basic_info.step_id
     *
     * @mbg.generated
     */
    public void setStepId(String stepId) {
        this.stepId = stepId == null ? null : stepId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_case_basic_info.priority
     *
     * @return the value of ts_case_basic_info.priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_case_basic_info.priority
     *
     * @param priority the value for ts_case_basic_info.priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_case_basic_info.is_invalid
     *
     * @return the value of ts_case_basic_info.is_invalid
     *
     * @mbg.generated
     */
    public Boolean getIsInvalid() {
        return isInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_case_basic_info.is_invalid
     *
     * @param isInvalid the value for ts_case_basic_info.is_invalid
     *
     * @mbg.generated
     */
    public void setIsInvalid(Boolean isInvalid) {
        this.isInvalid = isInvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_case_basic_info.create_time
     *
     * @return the value of ts_case_basic_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_case_basic_info.create_time
     *
     * @param createTime the value for ts_case_basic_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_case_basic_info.create_by
     *
     * @return the value of ts_case_basic_info.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_case_basic_info.create_by
     *
     * @param createBy the value for ts_case_basic_info.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_case_basic_info.update_time
     *
     * @return the value of ts_case_basic_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_case_basic_info.update_time
     *
     * @param updateTime the value for ts_case_basic_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_case_basic_info.update_by
     *
     * @return the value of ts_case_basic_info.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_case_basic_info.update_by
     *
     * @param updateBy the value for ts_case_basic_info.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}