package com.bgw.testing.dao.bgw_automation.pojo;

import java.util.Date;

public class TsGroupInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_group_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_group_info.goup_name
     *
     * @mbg.generated
     */
    private String goupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_group_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_group_info.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_group_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_group_info.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_group_info.parent_id
     *
     * @mbg.generated
     */
    private byte[] parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_group_info.id
     *
     * @return the value of ts_group_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_group_info.id
     *
     * @param id the value for ts_group_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_group_info.goup_name
     *
     * @return the value of ts_group_info.goup_name
     *
     * @mbg.generated
     */
    public String getGoupName() {
        return goupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_group_info.goup_name
     *
     * @param goupName the value for ts_group_info.goup_name
     *
     * @mbg.generated
     */
    public void setGoupName(String goupName) {
        this.goupName = goupName == null ? null : goupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_group_info.create_time
     *
     * @return the value of ts_group_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_group_info.create_time
     *
     * @param createTime the value for ts_group_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_group_info.create_by
     *
     * @return the value of ts_group_info.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_group_info.create_by
     *
     * @param createBy the value for ts_group_info.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_group_info.update_time
     *
     * @return the value of ts_group_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_group_info.update_time
     *
     * @param updateTime the value for ts_group_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_group_info.update_by
     *
     * @return the value of ts_group_info.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_group_info.update_by
     *
     * @param updateBy the value for ts_group_info.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_group_info.parent_id
     *
     * @return the value of ts_group_info.parent_id
     *
     * @mbg.generated
     */
    public byte[] getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_group_info.parent_id
     *
     * @param parentId the value for ts_group_info.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(byte[] parentId) {
        this.parentId = parentId;
    }
}