package com.bgw.testing.dao.bgw_automation.pojo;

import java.util.Date;

public class TsInterfaceBasicInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_basic_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_basic_info.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_basic_info.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_basic_info.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_basic_info.expecteds_tatus_code
     *
     * @mbg.generated
     */
    private Integer expectedsTatusCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_basic_info.carate_time
     *
     * @mbg.generated
     */
    private Date carateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_basic_info.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_basic_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_basic_info.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_basic_info.id
     *
     * @return the value of ts_interface_basic_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_basic_info.id
     *
     * @param id the value for ts_interface_basic_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_basic_info.description
     *
     * @return the value of ts_interface_basic_info.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_basic_info.description
     *
     * @param description the value for ts_interface_basic_info.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_basic_info.path
     *
     * @return the value of ts_interface_basic_info.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_basic_info.path
     *
     * @param path the value for ts_interface_basic_info.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_basic_info.method
     *
     * @return the value of ts_interface_basic_info.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_basic_info.method
     *
     * @param method the value for ts_interface_basic_info.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_basic_info.expecteds_tatus_code
     *
     * @return the value of ts_interface_basic_info.expecteds_tatus_code
     *
     * @mbg.generated
     */
    public Integer getExpectedsTatusCode() {
        return expectedsTatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_basic_info.expecteds_tatus_code
     *
     * @param expectedsTatusCode the value for ts_interface_basic_info.expecteds_tatus_code
     *
     * @mbg.generated
     */
    public void setExpectedsTatusCode(Integer expectedsTatusCode) {
        this.expectedsTatusCode = expectedsTatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_basic_info.carate_time
     *
     * @return the value of ts_interface_basic_info.carate_time
     *
     * @mbg.generated
     */
    public Date getCarateTime() {
        return carateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_basic_info.carate_time
     *
     * @param carateTime the value for ts_interface_basic_info.carate_time
     *
     * @mbg.generated
     */
    public void setCarateTime(Date carateTime) {
        this.carateTime = carateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_basic_info.create_by
     *
     * @return the value of ts_interface_basic_info.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_basic_info.create_by
     *
     * @param createBy the value for ts_interface_basic_info.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_basic_info.update_time
     *
     * @return the value of ts_interface_basic_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_basic_info.update_time
     *
     * @param updateTime the value for ts_interface_basic_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_basic_info.update_by
     *
     * @return the value of ts_interface_basic_info.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_basic_info.update_by
     *
     * @param updateBy the value for ts_interface_basic_info.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}