package com.bgw.testing.dao.bgw_automation.pojo;

import java.util.Date;

public class TsInterfaceParameter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_parameter.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_parameter.interface_id
     *
     * @mbg.generated
     */
    private String interfaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_parameter.parameter_type
     *
     * @mbg.generated
     */
    private String parameterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_parameter.key
     *
     * @mbg.generated
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_parameter.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_parameter.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_parameter.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_parameter.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_parameter.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_parameter.id
     *
     * @return the value of ts_interface_parameter.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_parameter.id
     *
     * @param id the value for ts_interface_parameter.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_parameter.interface_id
     *
     * @return the value of ts_interface_parameter.interface_id
     *
     * @mbg.generated
     */
    public String getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_parameter.interface_id
     *
     * @param interfaceId the value for ts_interface_parameter.interface_id
     *
     * @mbg.generated
     */
    public void setInterfaceId(String interfaceId) {
        this.interfaceId = interfaceId == null ? null : interfaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_parameter.parameter_type
     *
     * @return the value of ts_interface_parameter.parameter_type
     *
     * @mbg.generated
     */
    public String getParameterType() {
        return parameterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_parameter.parameter_type
     *
     * @param parameterType the value for ts_interface_parameter.parameter_type
     *
     * @mbg.generated
     */
    public void setParameterType(String parameterType) {
        this.parameterType = parameterType == null ? null : parameterType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_parameter.key
     *
     * @return the value of ts_interface_parameter.key
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_parameter.key
     *
     * @param key the value for ts_interface_parameter.key
     *
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_parameter.value
     *
     * @return the value of ts_interface_parameter.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_parameter.value
     *
     * @param value the value for ts_interface_parameter.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_parameter.create_time
     *
     * @return the value of ts_interface_parameter.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_parameter.create_time
     *
     * @param createTime the value for ts_interface_parameter.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_parameter.create_by
     *
     * @return the value of ts_interface_parameter.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_parameter.create_by
     *
     * @param createBy the value for ts_interface_parameter.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_parameter.update_time
     *
     * @return the value of ts_interface_parameter.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_parameter.update_time
     *
     * @param updateTime the value for ts_interface_parameter.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_parameter.update_by
     *
     * @return the value of ts_interface_parameter.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_parameter.update_by
     *
     * @param updateBy the value for ts_interface_parameter.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}