package com.bgw.testing.dao.bgw_automation.pojo;

public class TsInterfaceBasicInfoWithBLOBs extends TsInterfaceBasicInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_basic_info.body
     *
     * @mbg.generated
     */
    private String body;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_interface_basic_info.key_in_case_variable
     *
     * @mbg.generated
     */
    private String keyInCaseVariable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_basic_info.body
     *
     * @return the value of ts_interface_basic_info.body
     *
     * @mbg.generated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_basic_info.body
     *
     * @param body the value for ts_interface_basic_info.body
     *
     * @mbg.generated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_interface_basic_info.key_in_case_variable
     *
     * @return the value of ts_interface_basic_info.key_in_case_variable
     *
     * @mbg.generated
     */
    public String getKeyInCaseVariable() {
        return keyInCaseVariable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_interface_basic_info.key_in_case_variable
     *
     * @param keyInCaseVariable the value for ts_interface_basic_info.key_in_case_variable
     *
     * @mbg.generated
     */
    public void setKeyInCaseVariable(String keyInCaseVariable) {
        this.keyInCaseVariable = keyInCaseVariable == null ? null : keyInCaseVariable.trim();
    }
}