package com.bgw.testing.dao.bgw_automation.pojo;

import java.util.Date;

public class TsMysqlInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_mysql_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_mysql_info.case_id
     *
     * @mbg.generated
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_mysql_info.step_id
     *
     * @mbg.generated
     */
    private String stepId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_mysql_info.dao
     *
     * @mbg.generated
     */
    private String dao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_mysql_info.sql
     *
     * @mbg.generated
     */
    private String sql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_mysql_info.params
     *
     * @mbg.generated
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_mysql_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_mysql_info.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_mysql_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_mysql_info.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_mysql_info.id
     *
     * @return the value of ts_mysql_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_mysql_info.id
     *
     * @param id the value for ts_mysql_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_mysql_info.case_id
     *
     * @return the value of ts_mysql_info.case_id
     *
     * @mbg.generated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_mysql_info.case_id
     *
     * @param caseId the value for ts_mysql_info.case_id
     *
     * @mbg.generated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_mysql_info.step_id
     *
     * @return the value of ts_mysql_info.step_id
     *
     * @mbg.generated
     */
    public String getStepId() {
        return stepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_mysql_info.step_id
     *
     * @param stepId the value for ts_mysql_info.step_id
     *
     * @mbg.generated
     */
    public void setStepId(String stepId) {
        this.stepId = stepId == null ? null : stepId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_mysql_info.dao
     *
     * @return the value of ts_mysql_info.dao
     *
     * @mbg.generated
     */
    public String getDao() {
        return dao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_mysql_info.dao
     *
     * @param dao the value for ts_mysql_info.dao
     *
     * @mbg.generated
     */
    public void setDao(String dao) {
        this.dao = dao == null ? null : dao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_mysql_info.sql
     *
     * @return the value of ts_mysql_info.sql
     *
     * @mbg.generated
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_mysql_info.sql
     *
     * @param sql the value for ts_mysql_info.sql
     *
     * @mbg.generated
     */
    public void setSql(String sql) {
        this.sql = sql == null ? null : sql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_mysql_info.params
     *
     * @return the value of ts_mysql_info.params
     *
     * @mbg.generated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_mysql_info.params
     *
     * @param params the value for ts_mysql_info.params
     *
     * @mbg.generated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_mysql_info.create_time
     *
     * @return the value of ts_mysql_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_mysql_info.create_time
     *
     * @param createTime the value for ts_mysql_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_mysql_info.create_by
     *
     * @return the value of ts_mysql_info.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_mysql_info.create_by
     *
     * @param createBy the value for ts_mysql_info.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_mysql_info.update_time
     *
     * @return the value of ts_mysql_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_mysql_info.update_time
     *
     * @param updateTime the value for ts_mysql_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_mysql_info.update_by
     *
     * @return the value of ts_mysql_info.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_mysql_info.update_by
     *
     * @param updateBy the value for ts_mysql_info.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}