package com.bgw.testing.dao.bgw_automation.pojo;

import java.util.Date;

public class TsReportResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_report_result.batch_no
     *
     * @mbg.generated
     */
    private String batchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_report_result.task_id
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_report_result.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_report_result.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_report_result.total_num
     *
     * @mbg.generated
     */
    private Integer totalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_report_result.succ_num
     *
     * @mbg.generated
     */
    private Integer succNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_report_result.fail_num
     *
     * @mbg.generated
     */
    private Integer failNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_report_result.pass_rate
     *
     * @mbg.generated
     */
    private String passRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_report_result.executor
     *
     * @mbg.generated
     */
    private String executor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_report_result.batch_no
     *
     * @return the value of ts_report_result.batch_no
     *
     * @mbg.generated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_report_result.batch_no
     *
     * @param batchNo the value for ts_report_result.batch_no
     *
     * @mbg.generated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_report_result.task_id
     *
     * @return the value of ts_report_result.task_id
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_report_result.task_id
     *
     * @param taskId the value for ts_report_result.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_report_result.start_time
     *
     * @return the value of ts_report_result.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_report_result.start_time
     *
     * @param startTime the value for ts_report_result.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_report_result.end_time
     *
     * @return the value of ts_report_result.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_report_result.end_time
     *
     * @param endTime the value for ts_report_result.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_report_result.total_num
     *
     * @return the value of ts_report_result.total_num
     *
     * @mbg.generated
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_report_result.total_num
     *
     * @param totalNum the value for ts_report_result.total_num
     *
     * @mbg.generated
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_report_result.succ_num
     *
     * @return the value of ts_report_result.succ_num
     *
     * @mbg.generated
     */
    public Integer getSuccNum() {
        return succNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_report_result.succ_num
     *
     * @param succNum the value for ts_report_result.succ_num
     *
     * @mbg.generated
     */
    public void setSuccNum(Integer succNum) {
        this.succNum = succNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_report_result.fail_num
     *
     * @return the value of ts_report_result.fail_num
     *
     * @mbg.generated
     */
    public Integer getFailNum() {
        return failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_report_result.fail_num
     *
     * @param failNum the value for ts_report_result.fail_num
     *
     * @mbg.generated
     */
    public void setFailNum(Integer failNum) {
        this.failNum = failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_report_result.pass_rate
     *
     * @return the value of ts_report_result.pass_rate
     *
     * @mbg.generated
     */
    public String getPassRate() {
        return passRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_report_result.pass_rate
     *
     * @param passRate the value for ts_report_result.pass_rate
     *
     * @mbg.generated
     */
    public void setPassRate(String passRate) {
        this.passRate = passRate == null ? null : passRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_report_result.executor
     *
     * @return the value of ts_report_result.executor
     *
     * @mbg.generated
     */
    public String getExecutor() {
        return executor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_report_result.executor
     *
     * @param executor the value for ts_report_result.executor
     *
     * @mbg.generated
     */
    public void setExecutor(String executor) {
        this.executor = executor == null ? null : executor.trim();
    }
}