package com.bgw.testing.dao.bgw_automation.pojo;

import java.util.Date;

public class TsResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.resource_code
     *
     * @mbg.generated
     */
    private String resourceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.resource_name
     *
     * @mbg.generated
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.resource_url
     *
     * @mbg.generated
     */
    private String resourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.resource_icon_id
     *
     * @mbg.generated
     */
    private String resourceIconId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.resource_level
     *
     * @mbg.generated
     */
    private Integer resourceLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.resource_order
     *
     * @mbg.generated
     */
    private Integer resourceOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.resource_type
     *
     * @mbg.generated
     */
    private String resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_resource.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.id
     *
     * @return the value of ts_resource.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.id
     *
     * @param id the value for ts_resource.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.resource_code
     *
     * @return the value of ts_resource.resource_code
     *
     * @mbg.generated
     */
    public String getResourceCode() {
        return resourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.resource_code
     *
     * @param resourceCode the value for ts_resource.resource_code
     *
     * @mbg.generated
     */
    public void setResourceCode(String resourceCode) {
        this.resourceCode = resourceCode == null ? null : resourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.resource_name
     *
     * @return the value of ts_resource.resource_name
     *
     * @mbg.generated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.resource_name
     *
     * @param resourceName the value for ts_resource.resource_name
     *
     * @mbg.generated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.parent_id
     *
     * @return the value of ts_resource.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.parent_id
     *
     * @param parentId the value for ts_resource.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.resource_url
     *
     * @return the value of ts_resource.resource_url
     *
     * @mbg.generated
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.resource_url
     *
     * @param resourceUrl the value for ts_resource.resource_url
     *
     * @mbg.generated
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.resource_icon_id
     *
     * @return the value of ts_resource.resource_icon_id
     *
     * @mbg.generated
     */
    public String getResourceIconId() {
        return resourceIconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.resource_icon_id
     *
     * @param resourceIconId the value for ts_resource.resource_icon_id
     *
     * @mbg.generated
     */
    public void setResourceIconId(String resourceIconId) {
        this.resourceIconId = resourceIconId == null ? null : resourceIconId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.resource_level
     *
     * @return the value of ts_resource.resource_level
     *
     * @mbg.generated
     */
    public Integer getResourceLevel() {
        return resourceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.resource_level
     *
     * @param resourceLevel the value for ts_resource.resource_level
     *
     * @mbg.generated
     */
    public void setResourceLevel(Integer resourceLevel) {
        this.resourceLevel = resourceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.resource_order
     *
     * @return the value of ts_resource.resource_order
     *
     * @mbg.generated
     */
    public Integer getResourceOrder() {
        return resourceOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.resource_order
     *
     * @param resourceOrder the value for ts_resource.resource_order
     *
     * @mbg.generated
     */
    public void setResourceOrder(Integer resourceOrder) {
        this.resourceOrder = resourceOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.resource_type
     *
     * @return the value of ts_resource.resource_type
     *
     * @mbg.generated
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.resource_type
     *
     * @param resourceType the value for ts_resource.resource_type
     *
     * @mbg.generated
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.status
     *
     * @return the value of ts_resource.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.status
     *
     * @param status the value for ts_resource.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.remark
     *
     * @return the value of ts_resource.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.remark
     *
     * @param remark the value for ts_resource.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.create_time
     *
     * @return the value of ts_resource.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.create_time
     *
     * @param createTime the value for ts_resource.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.create_by
     *
     * @return the value of ts_resource.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.create_by
     *
     * @param createBy the value for ts_resource.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.update_time
     *
     * @return the value of ts_resource.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.update_time
     *
     * @param updateTime the value for ts_resource.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_resource.update_by
     *
     * @return the value of ts_resource.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_resource.update_by
     *
     * @param updateBy the value for ts_resource.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}