package com.bgw.testing.dao.bgw_automation.pojo;

import java.util.Date;

public class TsRedisInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.case_id
     *
     * @mbg.generated
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.step_id
     *
     * @mbg.generated
     */
    private String stepId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.db_index
     *
     * @mbg.generated
     */
    private Integer dbIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.key
     *
     * @mbg.generated
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.expire
     *
     * @mbg.generated
     */
    private Integer expire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_redis_info.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.id
     *
     * @return the value of ts_redis_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.id
     *
     * @param id the value for ts_redis_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.case_id
     *
     * @return the value of ts_redis_info.case_id
     *
     * @mbg.generated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.case_id
     *
     * @param caseId the value for ts_redis_info.case_id
     *
     * @mbg.generated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.step_id
     *
     * @return the value of ts_redis_info.step_id
     *
     * @mbg.generated
     */
    public String getStepId() {
        return stepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.step_id
     *
     * @param stepId the value for ts_redis_info.step_id
     *
     * @mbg.generated
     */
    public void setStepId(String stepId) {
        this.stepId = stepId == null ? null : stepId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.db_index
     *
     * @return the value of ts_redis_info.db_index
     *
     * @mbg.generated
     */
    public Integer getDbIndex() {
        return dbIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.db_index
     *
     * @param dbIndex the value for ts_redis_info.db_index
     *
     * @mbg.generated
     */
    public void setDbIndex(Integer dbIndex) {
        this.dbIndex = dbIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.key
     *
     * @return the value of ts_redis_info.key
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.key
     *
     * @param key the value for ts_redis_info.key
     *
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.value
     *
     * @return the value of ts_redis_info.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.value
     *
     * @param value the value for ts_redis_info.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.expire
     *
     * @return the value of ts_redis_info.expire
     *
     * @mbg.generated
     */
    public Integer getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.expire
     *
     * @param expire the value for ts_redis_info.expire
     *
     * @mbg.generated
     */
    public void setExpire(Integer expire) {
        this.expire = expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.action
     *
     * @return the value of ts_redis_info.action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.action
     *
     * @param action the value for ts_redis_info.action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.create_time
     *
     * @return the value of ts_redis_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.create_time
     *
     * @param createTime the value for ts_redis_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.create_by
     *
     * @return the value of ts_redis_info.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.create_by
     *
     * @param createBy the value for ts_redis_info.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.update_time
     *
     * @return the value of ts_redis_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.update_time
     *
     * @param updateTime the value for ts_redis_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_redis_info.update_by
     *
     * @return the value of ts_redis_info.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_redis_info.update_by
     *
     * @param updateBy the value for ts_redis_info.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}