package com.bgw.testing.dao.bgw_automation.pojo;

import java.util.Date;

public class TsStepBasicInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.case_id
     *
     * @mbg.generated
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.step_type
     *
     * @mbg.generated
     */
    private String stepType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.condition
     *
     * @mbg.generated
     */
    private String condition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.interface_id
     *
     * @mbg.generated
     */
    private String interfaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.func_value
     *
     * @mbg.generated
     */
    private String funcValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.init_case_variables
     *
     * @mbg.generated
     */
    private String initCaseVariables;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.key_in_global_variable
     *
     * @mbg.generated
     */
    private String keyInGlobalVariable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.key_in_environment_variable
     *
     * @mbg.generated
     */
    private String keyInEnvironmentVariable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.key_in_case_variable
     *
     * @mbg.generated
     */
    private String keyInCaseVariable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.element
     *
     * @mbg.generated
     */
    private String element;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.extractor
     *
     * @mbg.generated
     */
    private String extractor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.verifier
     *
     * @mbg.generated
     */
    private String verifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_step_basic_info.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.id
     *
     * @return the value of ts_step_basic_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.id
     *
     * @param id the value for ts_step_basic_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.case_id
     *
     * @return the value of ts_step_basic_info.case_id
     *
     * @mbg.generated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.case_id
     *
     * @param caseId the value for ts_step_basic_info.case_id
     *
     * @mbg.generated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.step_type
     *
     * @return the value of ts_step_basic_info.step_type
     *
     * @mbg.generated
     */
    public String getStepType() {
        return stepType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.step_type
     *
     * @param stepType the value for ts_step_basic_info.step_type
     *
     * @mbg.generated
     */
    public void setStepType(String stepType) {
        this.stepType = stepType == null ? null : stepType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.description
     *
     * @return the value of ts_step_basic_info.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.description
     *
     * @param description the value for ts_step_basic_info.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.condition
     *
     * @return the value of ts_step_basic_info.condition
     *
     * @mbg.generated
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.condition
     *
     * @param condition the value for ts_step_basic_info.condition
     *
     * @mbg.generated
     */
    public void setCondition(String condition) {
        this.condition = condition == null ? null : condition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.interface_id
     *
     * @return the value of ts_step_basic_info.interface_id
     *
     * @mbg.generated
     */
    public String getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.interface_id
     *
     * @param interfaceId the value for ts_step_basic_info.interface_id
     *
     * @mbg.generated
     */
    public void setInterfaceId(String interfaceId) {
        this.interfaceId = interfaceId == null ? null : interfaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.func_value
     *
     * @return the value of ts_step_basic_info.func_value
     *
     * @mbg.generated
     */
    public String getFuncValue() {
        return funcValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.func_value
     *
     * @param funcValue the value for ts_step_basic_info.func_value
     *
     * @mbg.generated
     */
    public void setFuncValue(String funcValue) {
        this.funcValue = funcValue == null ? null : funcValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.init_case_variables
     *
     * @return the value of ts_step_basic_info.init_case_variables
     *
     * @mbg.generated
     */
    public String getInitCaseVariables() {
        return initCaseVariables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.init_case_variables
     *
     * @param initCaseVariables the value for ts_step_basic_info.init_case_variables
     *
     * @mbg.generated
     */
    public void setInitCaseVariables(String initCaseVariables) {
        this.initCaseVariables = initCaseVariables == null ? null : initCaseVariables.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.key_in_global_variable
     *
     * @return the value of ts_step_basic_info.key_in_global_variable
     *
     * @mbg.generated
     */
    public String getKeyInGlobalVariable() {
        return keyInGlobalVariable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.key_in_global_variable
     *
     * @param keyInGlobalVariable the value for ts_step_basic_info.key_in_global_variable
     *
     * @mbg.generated
     */
    public void setKeyInGlobalVariable(String keyInGlobalVariable) {
        this.keyInGlobalVariable = keyInGlobalVariable == null ? null : keyInGlobalVariable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.key_in_environment_variable
     *
     * @return the value of ts_step_basic_info.key_in_environment_variable
     *
     * @mbg.generated
     */
    public String getKeyInEnvironmentVariable() {
        return keyInEnvironmentVariable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.key_in_environment_variable
     *
     * @param keyInEnvironmentVariable the value for ts_step_basic_info.key_in_environment_variable
     *
     * @mbg.generated
     */
    public void setKeyInEnvironmentVariable(String keyInEnvironmentVariable) {
        this.keyInEnvironmentVariable = keyInEnvironmentVariable == null ? null : keyInEnvironmentVariable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.key_in_case_variable
     *
     * @return the value of ts_step_basic_info.key_in_case_variable
     *
     * @mbg.generated
     */
    public String getKeyInCaseVariable() {
        return keyInCaseVariable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.key_in_case_variable
     *
     * @param keyInCaseVariable the value for ts_step_basic_info.key_in_case_variable
     *
     * @mbg.generated
     */
    public void setKeyInCaseVariable(String keyInCaseVariable) {
        this.keyInCaseVariable = keyInCaseVariable == null ? null : keyInCaseVariable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.element
     *
     * @return the value of ts_step_basic_info.element
     *
     * @mbg.generated
     */
    public String getElement() {
        return element;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.element
     *
     * @param element the value for ts_step_basic_info.element
     *
     * @mbg.generated
     */
    public void setElement(String element) {
        this.element = element == null ? null : element.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.extractor
     *
     * @return the value of ts_step_basic_info.extractor
     *
     * @mbg.generated
     */
    public String getExtractor() {
        return extractor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.extractor
     *
     * @param extractor the value for ts_step_basic_info.extractor
     *
     * @mbg.generated
     */
    public void setExtractor(String extractor) {
        this.extractor = extractor == null ? null : extractor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.verifier
     *
     * @return the value of ts_step_basic_info.verifier
     *
     * @mbg.generated
     */
    public String getVerifier() {
        return verifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.verifier
     *
     * @param verifier the value for ts_step_basic_info.verifier
     *
     * @mbg.generated
     */
    public void setVerifier(String verifier) {
        this.verifier = verifier == null ? null : verifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.create_time
     *
     * @return the value of ts_step_basic_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.create_time
     *
     * @param createTime the value for ts_step_basic_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.create_by
     *
     * @return the value of ts_step_basic_info.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.create_by
     *
     * @param createBy the value for ts_step_basic_info.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.update_time
     *
     * @return the value of ts_step_basic_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.update_time
     *
     * @param updateTime the value for ts_step_basic_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_step_basic_info.update_by
     *
     * @return the value of ts_step_basic_info.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_step_basic_info.update_by
     *
     * @param updateBy the value for ts_step_basic_info.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}