package com.bgw.testing.dao.bgw_automation.pojo;

import java.util.Date;

public class TsTaskConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_task_config.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_task_config.task_name
     *
     * @mbg.generated
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_task_config.environment_id
     *
     * @mbg.generated
     */
    private String environmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_task_config.cron
     *
     * @mbg.generated
     */
    private String cron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_task_config.run_method
     *
     * @mbg.generated
     */
    private String runMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_task_config.task_status
     *
     * @mbg.generated
     */
    private String taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_task_config.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_task_config.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_task_config.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_task_config.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_task_config.id
     *
     * @return the value of ts_task_config.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_task_config.id
     *
     * @param id the value for ts_task_config.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_task_config.task_name
     *
     * @return the value of ts_task_config.task_name
     *
     * @mbg.generated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_task_config.task_name
     *
     * @param taskName the value for ts_task_config.task_name
     *
     * @mbg.generated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_task_config.environment_id
     *
     * @return the value of ts_task_config.environment_id
     *
     * @mbg.generated
     */
    public String getEnvironmentId() {
        return environmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_task_config.environment_id
     *
     * @param environmentId the value for ts_task_config.environment_id
     *
     * @mbg.generated
     */
    public void setEnvironmentId(String environmentId) {
        this.environmentId = environmentId == null ? null : environmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_task_config.cron
     *
     * @return the value of ts_task_config.cron
     *
     * @mbg.generated
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_task_config.cron
     *
     * @param cron the value for ts_task_config.cron
     *
     * @mbg.generated
     */
    public void setCron(String cron) {
        this.cron = cron == null ? null : cron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_task_config.run_method
     *
     * @return the value of ts_task_config.run_method
     *
     * @mbg.generated
     */
    public String getRunMethod() {
        return runMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_task_config.run_method
     *
     * @param runMethod the value for ts_task_config.run_method
     *
     * @mbg.generated
     */
    public void setRunMethod(String runMethod) {
        this.runMethod = runMethod == null ? null : runMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_task_config.task_status
     *
     * @return the value of ts_task_config.task_status
     *
     * @mbg.generated
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_task_config.task_status
     *
     * @param taskStatus the value for ts_task_config.task_status
     *
     * @mbg.generated
     */
    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus == null ? null : taskStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_task_config.create_time
     *
     * @return the value of ts_task_config.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_task_config.create_time
     *
     * @param createTime the value for ts_task_config.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_task_config.create_by
     *
     * @return the value of ts_task_config.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_task_config.create_by
     *
     * @param createBy the value for ts_task_config.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_task_config.update_time
     *
     * @return the value of ts_task_config.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_task_config.update_time
     *
     * @param updateTime the value for ts_task_config.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_task_config.update_by
     *
     * @return the value of ts_task_config.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_task_config.update_by
     *
     * @param updateBy the value for ts_task_config.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}