package com.bgw.testing.dao.integration.mapper;

import com.bgw.testing.dao.integration.pojo.TCase;

public interface TCaseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_case
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_case
     *
     * @mbg.generated
     */
    int insert(TCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_case
     *
     * @mbg.generated
     */
    int insertSelective(TCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_case
     *
     * @mbg.generated
     */
    TCase selectByPrimaryKey(String caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_case
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCase record);
}