package com.bgw.testing.dao.usercenter.mapper;

import com.bgw.testing.dao.usercenter.pojo.UserBasic888888;

public interface UserBasic888888Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_888888
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_888888
     *
     * @mbg.generated
     */
    int insert(UserBasic888888 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_888888
     *
     * @mbg.generated
     */
    int insertSelective(UserBasic888888 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_888888
     *
     * @mbg.generated
     */
    UserBasic888888 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_888888
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserBasic888888 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_basic_888888
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserBasic888888 record);
}