package com.bgw.testing.dao.usercenter.pojo;

import java.util.Date;

public class UserBasic888888 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.login_pwd
     *
     * @mbg.generated
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.realname_status
     *
     * @mbg.generated
     */
    private String realnameStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.bank_info
     *
     * @mbg.generated
     */
    private String bankInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_basic_888888.pay_code
     *
     * @mbg.generated
     */
    private String payCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.id
     *
     * @return the value of user_basic_888888.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.id
     *
     * @param id the value for user_basic_888888.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.name
     *
     * @return the value of user_basic_888888.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.name
     *
     * @param name the value for user_basic_888888.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.login_pwd
     *
     * @return the value of user_basic_888888.login_pwd
     *
     * @mbg.generated
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.login_pwd
     *
     * @param loginPwd the value for user_basic_888888.login_pwd
     *
     * @mbg.generated
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.status
     *
     * @return the value of user_basic_888888.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.status
     *
     * @param status the value for user_basic_888888.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.realname_status
     *
     * @return the value of user_basic_888888.realname_status
     *
     * @mbg.generated
     */
    public String getRealnameStatus() {
        return realnameStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.realname_status
     *
     * @param realnameStatus the value for user_basic_888888.realname_status
     *
     * @mbg.generated
     */
    public void setRealnameStatus(String realnameStatus) {
        this.realnameStatus = realnameStatus == null ? null : realnameStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.mobile
     *
     * @return the value of user_basic_888888.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.mobile
     *
     * @param mobile the value for user_basic_888888.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.bank_info
     *
     * @return the value of user_basic_888888.bank_info
     *
     * @mbg.generated
     */
    public String getBankInfo() {
        return bankInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.bank_info
     *
     * @param bankInfo the value for user_basic_888888.bank_info
     *
     * @mbg.generated
     */
    public void setBankInfo(String bankInfo) {
        this.bankInfo = bankInfo == null ? null : bankInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.id_card
     *
     * @return the value of user_basic_888888.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.id_card
     *
     * @param idCard the value for user_basic_888888.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.created_by
     *
     * @return the value of user_basic_888888.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.created_by
     *
     * @param createdBy the value for user_basic_888888.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.created_at
     *
     * @return the value of user_basic_888888.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.created_at
     *
     * @param createdAt the value for user_basic_888888.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.updated_by
     *
     * @return the value of user_basic_888888.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.updated_by
     *
     * @param updatedBy the value for user_basic_888888.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.updated_at
     *
     * @return the value of user_basic_888888.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.updated_at
     *
     * @param updatedAt the value for user_basic_888888.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_basic_888888.pay_code
     *
     * @return the value of user_basic_888888.pay_code
     *
     * @mbg.generated
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_basic_888888.pay_code
     *
     * @param payCode the value for user_basic_888888.pay_code
     *
     * @mbg.generated
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode == null ? null : payCode.trim();
    }
}